# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mypoc-wp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://poc4docker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c453a07dfd8b41589d0bc969475739d3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2c7ca8724e6e4b9facacc289f16c177c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: poc4docker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c453a07dfd8b41589d0bc969475739d3 }}/poc4docker/poc:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mypoc-wp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5d01be9d688944bea6a6594b70544aca }}
        images: 'poc4docker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c453a07dfd8b41589d0bc969475739d3 }}/poc4docker/poc:${{ github.sha }}'